// src/data.js
export const orphanCards = [
    {
      id: 1,
      image: "/f.png",
      title: "سارة",
      description: "كفالة مالية بمبلغ وقدره 250 ريال",
      region: "منطقة جدة",
      gender: "أنثى",
      parents: "معلوم الأم",
      age: "8 سنوات",
      health: "سليم",
    },
    {
      id: 2,
      image: "/logo.png",
      title: "محمد",
      description: "كفالة مالية بمبلغ وقدره 300 ريال",
      region: "منطقة الرياض",
      gender: "ذكر",
      parents: "يتيم الأب",
      age: "10 سنوات",
      health: "سليم",
    },
    {
      id: 3,
      image: "/d.png",
      title: "فاطمة",
      description: "كفالة مالية بمبلغ وقدره 200 ريال",
      region: "منطقة مكة المكرمة",
      gender: "أنثى",
      parents: "مجهول الوالدين",
      age: "6 سنوات",
      health: "سليم",
    },
    {
      id: 4,
      image: "/b.png",
      title: "علي",
      description: "كفالة مالية بمبلغ وقدره 350 ريال",
      region: "منطقة القصيم",
      gender: "ذكر",
      parents: "يتيم الأب والأم",
      age: "12 سنوات",
      health: "سليم",
    },
    {
      id: 5,
      image: "/a.png",
      title: "ليلى",
      description: "كفالة مالية بمبلغ وقدره 400 ريال",
      region: "منطقة المدينة المنورة",
      gender: "أنثى",
      parents: "معلوم الوالدين",
      age: "5 سنوات",
      health: "سليم",
    },
    {
      id: 6,
      image: "/f.png",
      title: "خالد",
      description: "كفالة مالية بمبلغ وقدره 500 ريال",
      region: "منطقة تبوك",
      gender: "ذكر",
      parents: "يتيم الأب",
      age: "15 سنوات",
      health: "سليم",
    },
    {
      id: 7,
      image: "/f.png",
      title: "ماجد",
      description: "كفالة مالية بمبلغ وقدره 250 ريال",
      region: "منطقة الرياض",
      gender: "أنثى",
      parents: "معلوم الأم",
      age: "13 سنوات",
      health: "سليم",
    },
  ];